package com.sn.designsystem.component.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = parseColor("#3384F9")
val md_theme_light_onPrimary = parseColor("#FFFFFFFF")
val md_theme_light_primaryContainer = parseColor("#FFD7E2FF")
val md_theme_light_onPrimaryContainer = parseColor("#FF001A40")
val md_theme_light_secondary = parseColor("#FF006874")
val md_theme_light_onSecondary = parseColor("#FFFFFFFF")
val md_theme_light_secondaryContainer = parseColor("#FF97F0FF")
val md_theme_light_onSecondaryContainer = parseColor("#FF001F24")
val md_theme_light_tertiary = parseColor("#FF006874")
val md_theme_light_onTertiary = parseColor("#FFFFFFFF")
val md_theme_light_tertiaryContainer = parseColor("#FF97F0FF")
val md_theme_light_onTertiaryContainer = parseColor("#FF001F24")
val md_theme_light_error = parseColor("#FFBA1A1A")
val md_theme_light_errorContainer = parseColor("#FFFFDA")
val md_theme_light_onError = parseColor("#FFFFFFFF")
val md_theme_light_onErrorContainer = parseColor("#FF410002")
val md_theme_light_background = parseColor("#FFF8FDFF")
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFFACC7FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF005BBE)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = parseColor("#FFACC7FF")
val md_theme_dark_onPrimary = parseColor("#FF002F67")
val md_theme_dark_primaryContainer = parseColor("#FF004491")
val md_theme_dark_onPrimaryContainer = parseColor("#FFD7E2FF")
val md_theme_dark_secondary = parseColor("#FF4FD8EB")
val md_theme_dark_onSecondary = parseColor("#FF00363D")
val md_theme_dark_secondaryContainer = parseColor("#FF004F58")
val md_theme_dark_onSecondaryContainer = parseColor("#FF97F0FF")
val md_theme_dark_tertiary = parseColor("#FF4FD8EB")
val md_theme_dark_onTertiary = parseColor("#FF00363D")
val md_theme_dark_tertiaryContainer = parseColor("#FF004F58")
val md_theme_dark_onTertiaryContainer = parseColor("#FF97F0FF")
val md_theme_dark_error = parseColor("#FFFFB4AB")
val md_theme_dark_errorContainer = parseColor("#FF93000A")
val md_theme_dark_onError = parseColor("#FF690005")
val md_theme_dark_onErrorContainer = parseColor("#FFFFDAD6")
val md_theme_dark_background = parseColor("#FF001F25")
val md_theme_dark_onBackground = parseColor("#FFA6EEFF")
val md_theme_dark_surface = parseColor("#FF001F25")
val md_theme_dark_onSurface = parseColor("#FFA6EEFF")
val md_theme_dark_surfaceVariant = parseColor("#FF44474E")
val md_theme_dark_onSurfaceVariant = parseColor("#FFC4C6D0")
val md_theme_dark_outline = parseColor("#FF8E9099")
val md_theme_dark_inverseOnSurface = parseColor("#FF001F25")
val md_theme_dark_inverseSurface = parseColor("#FFA6EEFF")
val md_theme_dark_inversePrimary = parseColor("#FF005BBE")
val md_theme_dark_shadow = parseColor("#FF000000")
val md_theme_dark_surfaceTint = parseColor("#FFACC7FF")
val md_theme_dark_outlineVariant = parseColor("#FF44474E")
val md_theme_dark_scrim = parseColor("#FF000000")


val seed = parseColor("#FF3384F9")

fun parseColor(hexColor: String): Color {
    val color = hexColor.substring(1)
    val r = color.substring(0, 2).toInt(16)
    val g = color.substring(2, 4).toInt(16)
    val b = color.substring(4, 6).toInt(16)
    return Color(r, g, b)
}